# Generated by Django 5.2.3 on 2025-06-20 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='agent_pairing_token',
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='agent_pairing_token_expires',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
