# Generated by Django 5.2.3 on 2025-06-30 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_agent_pairing_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Optional phone number, e.g., +12223334444', max_length=17, null=True),
        ),
    ]
