# Generated by Django 5.2.3 on 2025-06-30 07:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminFeatureRestrictions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_use_activity_monitoring', models.BooleanField(default=True, help_text='Allow basic activity tracking')),
                ('can_use_network_monitoring', models.BooleanField(default=True, help_text='Allow network usage monitoring')),
                ('can_use_screenshot_capturing', models.BooleanField(default=True, help_text='Allow screenshot capture')),
                ('can_use_live_streaming', models.BooleanField(default=False, help_text='Allow live screen streaming')),
                ('can_use_video_recording', models.BooleanField(default=False, help_text='Allow video recording')),
                ('can_use_keystroke_logging', models.BooleanField(default=False, help_text='Allow keystroke logging')),
                ('can_use_email_monitoring', models.BooleanField(default=False, help_text='Allow email monitoring')),
                ('can_configure_monitoring', models.BooleanField(default=True, help_text='Allow configuring monitoring settings')),
                ('can_manage_email_config', models.BooleanField(default=True, help_text='Allow email server configuration')),
                ('max_screenshot_retention_days', models.IntegerField(default=30, help_text='Maximum days to retain screenshots')),
                ('max_video_retention_days', models.IntegerField(default=7, help_text='Maximum days to retain videos')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admin', models.OneToOneField(limit_choices_to={'role': 'ADMIN'}, on_delete=django.db.models.deletion.CASCADE, related_name='feature_restrictions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Admin Feature Restriction',
                'verbose_name_plural': 'Admin Feature Restrictions',
            },
        ),
    ]
