# Generated by Django 5.2.3 on 2025-07-05 05:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_add_admin_feature_restrictions'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyBreakSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Break name (e.g., 'Lunch Break', 'Coffee Break')", max_length=100)),
                ('day', models.CharField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday'), ('sunday', 'Sunday'), ('daily', 'Every Day')], default='daily', max_length=10)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admin', models.ForeignKey(limit_choices_to={'role': 'ADMIN'}, on_delete=django.db.models.deletion.CASCADE, related_name='company_break_schedules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Company Break Schedule',
                'verbose_name_plural': 'Company Break Schedules',
                'ordering': ['day', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='UserBreakSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Break name (e.g., 'Personal Break', 'Medical Appointment')", max_length=100)),
                ('day', models.CharField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday'), ('sunday', 'Sunday'), ('daily', 'Every Day')], default='daily', max_length=10)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('is_on_leave', models.BooleanField(default=False, help_text='User is on extended leave')),
                ('leave_start_date', models.DateField(blank=True, null=True)),
                ('leave_end_date', models.DateField(blank=True, null=True)),
                ('leave_reason', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(limit_choices_to={'role': 'USER'}, on_delete=django.db.models.deletion.CASCADE, related_name='user_break_schedules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Break Schedule',
                'verbose_name_plural': 'User Break Schedules',
                'ordering': ['day', 'start_time'],
            },
        ),
    ]
