# Generated by Django 5.2.3 on 2025-06-21 06:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_address', models.EmailField(max_length=254, unique=True)),
                ('encrypted_app_password', models.CharField(max_length=256)),
                ('imap_server', models.CharField(max_length=100)),
                ('imap_port', models.PositiveIntegerField(default=993)),
                ('smtp_server', models.CharField(blank=True, max_length=100, null=True)),
                ('smtp_port', models.PositiveIntegerField(blank=True, default=587, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to disable monitoring.')),
                ('last_checked_inbox', models.DateTimeField(blank=True, null=True)),
                ('last_checked_sent', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MonitoredEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('folder', models.CharField(max_length=50)),
                ('sender', models.CharField(max_length=255)),
                ('recipients', models.TextField()),
                ('subject', models.CharField(max_length=512)),
                ('body', models.TextField()),
                ('date', models.DateTimeField()),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='mail_monitor.emailaccount')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
