# Generated by Django 5.2.3 on 2025-06-21 07:14

import django.db.models.deletion
import mail_monitor.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail_monitor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitoredemail',
            name='has_attachments',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='monitoredemail',
            name='folder',
            field=models.CharField(help_text='e.g., INBOX, Sent', max_length=50),
        ),
        migrations.AlterField(
            model_name='monitoredemail',
            name='recipients',
            field=models.TextField(help_text='Comma-separated list of recipients (To, Cc, Bcc)'),
        ),
        migrations.CreateModel(
            name='EmailAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=mail_monitor.models.attachment_upload_path)),
                ('filename', models.CharField(max_length=255)),
                ('content_type', models.CharField(max_length=100)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='mail_monitor.monitoredemail')),
            ],
        ),
    ]
