# Generated by Django 5.2.3 on 2025-06-21 08:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail_monitor', '0002_monitoredemail_has_attachments_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='monitoredemail',
            options={'ordering': ['date']},
        ),
        migrations.AddField(
            model_name='emailaccount',
            name='last_inbox_uid',
            field=models.PositiveIntegerField(blank=True, help_text='The last Unique ID fetched from the INBOX.', null=True),
        ),
        migrations.AddField(
            model_name='emailaccount',
            name='last_sent_uid',
            field=models.PositiveIntegerField(blank=True, help_text='The last Unique ID fetched from the Sent folder.', null=True),
        ),
        migrations.AddField(
            model_name='monitoredemail',
            name='in_reply_to_header',
            field=models.CharField(blank=True, db_index=True, help_text='The Message-ID of the email this is a reply to.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='monitoredemail',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='mail_monitor.monitoredemail'),
        ),
        migrations.AddField(
            model_name='monitoredemail',
            name='uid',
            field=models.PositiveIntegerField(db_index=True, default=1, help_text='The Unique ID of the email within its specific folder.'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='emailaccount',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='monitoredemail',
            name='folder',
            field=models.CharField(help_text="The mailbox folder this email was fetched from (e.g., 'INBOX', 'Sent').", max_length=50),
        ),
        migrations.AlterField(
            model_name='monitoredemail',
            name='message_id',
            field=models.CharField(db_index=True, help_text='The globally unique Message-ID from the email header.', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='monitoredemail',
            name='recipients',
            field=models.TextField(help_text='A string containing all To, Cc, and Bcc recipients.'),
        ),
        migrations.AlterUniqueTogether(
            name='monitoredemail',
            unique_together={('account', 'folder', 'uid')},
        ),
    ]
