# Generated by Django 5.2.3 on 2025-06-21 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail_monitor', '0003_alter_monitoredemail_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monitoredemail',
            name='recipients',
        ),
        migrations.AddField(
            model_name='monitoredemail',
            name='bcc_recipients',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='monitoredemail',
            name='cc_recipients',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='monitoredemail',
            name='to_recipients',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='emailaccount',
            name='is_active',
            field=models.BooleanField(default=True, help_text="Controlled by the Admin's activation of the user."),
        ),
        migrations.AlterField(
            model_name='monitoredemail',
            name='body',
            field=models.TextField(help_text='Stores the rich HTML body of the email.'),
        ),
        migrations.AlterField(
            model_name='monitoredemail',
            name='in_reply_to_header',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
    ]
