# Generated by Django 5.2.3 on 2025-06-23 06:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail_monitor', '0004_remove_monitoredemail_recipients_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='monitoredemail',
            options={'ordering': ['-date']},
        ),
        migrations.AlterUniqueTogether(
            name='monitoredemail',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='emailaccount',
            name='email_address',
        ),
        migrations.RemoveField(
            model_name='emailaccount',
            name='imap_port',
        ),
        migrations.RemoveField(
            model_name='emailaccount',
            name='imap_server',
        ),
        migrations.RemoveField(
            model_name='emailaccount',
            name='last_checked_inbox',
        ),
        migrations.RemoveField(
            model_name='emailaccount',
            name='last_checked_sent',
        ),
        migrations.RemoveField(
            model_name='emailaccount',
            name='last_inbox_uid',
        ),
        migrations.RemoveField(
            model_name='emailaccount',
            name='last_sent_uid',
        ),
        migrations.RemoveField(
            model_name='emailaccount',
            name='smtp_port',
        ),
        migrations.RemoveField(
            model_name='emailaccount',
            name='smtp_server',
        ),
        migrations.AddField(
            model_name='monitoredemail',
            name='recipients',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='emailaccount',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='monitoredemail',
            name='body',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='monitoredemail',
            name='folder',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='monitoredemail',
            name='message_id',
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
        migrations.CreateModel(
            name='CompanyEmailConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imap_server', models.CharField(max_length=100)),
                ('imap_port', models.PositiveIntegerField(default=993)),
                ('smtp_server', models.CharField(blank=True, max_length=100, null=True)),
                ('smtp_port', models.PositiveIntegerField(blank=True, default=587, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admin', models.OneToOneField(help_text='The Admin user who owns this configuration.', limit_choices_to={'role': 'ADMIN'}, on_delete=django.db.models.deletion.CASCADE, related_name='email_config', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='monitoredemail',
            name='bcc_recipients',
        ),
        migrations.RemoveField(
            model_name='monitoredemail',
            name='cc_recipients',
        ),
        migrations.RemoveField(
            model_name='monitoredemail',
            name='in_reply_to_header',
        ),
        migrations.RemoveField(
            model_name='monitoredemail',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='monitoredemail',
            name='to_recipients',
        ),
        migrations.RemoveField(
            model_name='monitoredemail',
            name='uid',
        ),
    ]
