# Generated by Django 5.2.3 on 2025-06-23 06:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail_monitor', '0005_alter_monitoredemail_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='monitoredemail',
            options={'ordering': ['-date'], 'verbose_name': 'Monitored Email', 'verbose_name_plural': 'Monitored Emails'},
        ),
        migrations.RemoveField(
            model_name='monitoredemail',
            name='folder',
        ),
        migrations.RemoveField(
            model_name='monitoredemail',
            name='recipients',
        ),
        migrations.AddField(
            model_name='monitoredemail',
            name='direction',
            field=models.CharField(choices=[('IN', 'Incoming'), ('OUT', 'Outgoing')], default=1, max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='monitoredemail',
            name='recipients_bcc',
            field=models.TextField(blank=True, help_text="Recipients in the 'Bcc' field."),
        ),
        migrations.AddField(
            model_name='monitoredemail',
            name='recipients_cc',
            field=models.TextField(blank=True, help_text="Recipients in the 'Cc' field."),
        ),
        migrations.AddField(
            model_name='monitoredemail',
            name='recipients_to',
            field=models.TextField(blank=True, help_text="Recipients in the 'To' field."),
        ),
        migrations.AlterField(
            model_name='emailaccount',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='email_account', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='monitoredemail',
            name='sender',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='monitoredemail',
            name='subject',
            field=models.CharField(max_length=1024),
        ),
    ]
