# Generated by Django 5.2.3 on 2025-06-23 07:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail_monitor', '0006_alter_monitoredemail_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='monitoredemail',
            options={'ordering': ['date']},
        ),
        migrations.AddField(
            model_name='monitoredemail',
            name='in_reply_to_header',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='monitoredemail',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='mail_monitor.monitoredemail'),
        ),
        migrations.AlterField(
            model_name='monitoredemail',
            name='recipients_bcc',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='monitoredemail',
            name='recipients_cc',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='monitoredemail',
            name='recipients_to',
            field=models.TextField(blank=True),
        ),
    ]
