# Generated by Django 5.2.3 on 2025-06-23 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail_monitor', '0007_alter_monitoredemail_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailaccount',
            name='last_inbox_uid',
            field=models.PositiveIntegerField(blank=True, help_text='The UID of the last email fetched from the inbox.', null=True),
        ),
        migrations.AddField(
            model_name='emailaccount',
            name='last_sent_uid',
            field=models.PositiveIntegerField(blank=True, help_text='The UID of the last email fetched from the sent folder.', null=True),
        ),
    ]
