# Generated by Django 5.2.3 on 2025-06-23 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail_monitor', '0008_emailaccount_last_inbox_uid_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companyemailconfig',
            options={'verbose_name': 'Company Email Configuration', 'verbose_name_plural': 'Company Email Configurations'},
        ),
        migrations.AlterModelOptions(
            name='emailaccount',
            options={'verbose_name': 'User Email Account', 'verbose_name_plural': 'User Email Accounts'},
        ),
        migrations.AlterModelOptions(
            name='emailattachment',
            options={'verbose_name': 'Email Attachment', 'verbose_name_plural': 'Email Attachments'},
        ),
        migrations.AlterModelOptions(
            name='monitoredemail',
            options={'ordering': ['-date'], 'verbose_name': 'Monitored Email', 'verbose_name_plural': 'Monitored Emails'},
        ),
        migrations.AddField(
            model_name='emailaccount',
            name='is_authenticated',
            field=models.BooleanField(default=False, help_text='True if a successful IMAP login has occurred with the stored credentials.'),
        ),
        migrations.AddField(
            model_name='emailaccount',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='companyemailconfig',
            name='imap_server',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='companyemailconfig',
            name='smtp_server',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='emailaccount',
            name='encrypted_app_password',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='emailaccount',
            name='is_active',
            field=models.BooleanField(default=True, help_text="Controlled by the Admin's activate/deactivate actions."),
        ),
        migrations.AlterField(
            model_name='emailattachment',
            name='content_type',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='monitoredemail',
            name='date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='monitoredemail',
            name='direction',
            field=models.CharField(choices=[('IN', 'Incoming'), ('OUT', 'Outgoing')], db_index=True, max_length=3),
        ),
        migrations.AlterField(
            model_name='monitoredemail',
            name='in_reply_to_header',
            field=models.CharField(blank=True, db_index=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='monitoredemail',
            name='message_id',
            field=models.CharField(db_index=True, max_length=512, unique=True),
        ),
        migrations.AlterField(
            model_name='monitoredemail',
            name='sender',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='monitoredemail',
            name='subject',
            field=models.TextField(blank=True),
        ),
    ]
