# Generated by Django 5.2.3 on 2025-06-20 07:25

import django.db.models.deletion
import monitor_app.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_id', models.CharField(db_index=True, max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('window_title', models.CharField(blank=True, max_length=512, null=True)),
                ('active_browser_url', models.CharField(blank=True, max_length=2048, null=True)),
                ('screenshot', models.ImageField(blank=True, null=True, upload_to=monitor_app.models.screenshot_upload_path)),
                ('keystroke_count', models.PositiveIntegerField(default=0)),
                ('mouse_event_count', models.PositiveIntegerField(default=0)),
                ('upload_bytes', models.BigIntegerField(default=0)),
                ('download_bytes', models.BigIntegerField(default=0)),
                ('network_type', models.CharField(blank=True, max_length=255, null=True)),
                ('productive_status', models.CharField(default='N/A', max_length=50)),
                ('typed_keys', models.TextField(blank=True, null=True)),
                ('is_activity_monitoring_enabled', models.BooleanField(default=True)),
                ('is_network_monitoring_enabled', models.BooleanField(default=True)),
                ('capture_interval_seconds', models.IntegerField(default=10)),
            ],
            options={
                'verbose_name_plural': 'Agent Data Logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_id', models.CharField(max_length=255, unique=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('window_title', models.CharField(blank=True, max_length=512, null=True)),
                ('active_browser_url', models.URLField(blank=True, max_length=2048, null=True)),
                ('keystroke_count', models.PositiveIntegerField(default=0)),
                ('mouse_event_count', models.PositiveIntegerField(default=0)),
                ('upload_bytes', models.BigIntegerField(default=0)),
                ('download_bytes', models.BigIntegerField(default=0)),
                ('network_type', models.CharField(blank=True, max_length=255, null=True)),
                ('is_recording', models.BooleanField(default=False)),
                ('productive_status', models.CharField(default='N/A', max_length=50)),
                ('typed_keys', models.TextField(blank=True, null=True)),
                ('is_activity_monitoring_enabled', models.BooleanField(default=True)),
                ('is_network_monitoring_enabled', models.BooleanField(default=True)),
                ('capture_interval_seconds', models.IntegerField(default=10, help_text='Data capture interval for the agent in seconds.')),
                ('monday_active_start', models.TimeField(blank=True, help_text='UTC time', null=True)),
                ('monday_active_end', models.TimeField(blank=True, help_text='UTC time', null=True)),
                ('tuesday_active_start', models.TimeField(blank=True, help_text='UTC time', null=True)),
                ('tuesday_active_end', models.TimeField(blank=True, help_text='UTC time', null=True)),
                ('wednesday_active_start', models.TimeField(blank=True, help_text='UTC time', null=True)),
                ('wednesday_active_end', models.TimeField(blank=True, help_text='UTC time', null=True)),
                ('thursday_active_start', models.TimeField(blank=True, help_text='UTC time', null=True)),
                ('thursday_active_end', models.TimeField(blank=True, help_text='UTC time', null=True)),
                ('friday_active_start', models.TimeField(blank=True, help_text='UTC time', null=True)),
                ('friday_active_end', models.TimeField(blank=True, help_text='UTC time', null=True)),
                ('saturday_active_start', models.TimeField(blank=True, help_text='UTC time', null=True)),
                ('saturday_active_end', models.TimeField(blank=True, help_text='UTC time', null=True)),
                ('sunday_active_start', models.TimeField(blank=True, help_text='UTC time', null=True)),
                ('sunday_active_end', models.TimeField(blank=True, help_text='UTC time', null=True)),
                ('user', models.ForeignKey(help_text='The employee user this agent is monitoring.', limit_choices_to={'role': 'USER'}, on_delete=django.db.models.deletion.CASCADE, related_name='agents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Agents',
                'ordering': ['user__email', 'agent_id'],
            },
        ),
        migrations.CreateModel(
            name='KeyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('source_app', models.CharField(help_text='The application or website where keys were typed.', max_length=255)),
                ('key_sequence', models.TextField(help_text='The sequence of keystrokes captured during the session.')),
                ('is_messaging_log', models.BooleanField(default=False, help_text='True if the source was identified as a messaging app.')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='key_logs', to='monitor_app.agent')),
            ],
            options={
                'verbose_name_plural': 'Key Logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='RecordedVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('video_file', models.FileField(upload_to=monitor_app.models.video_upload_path)),
                ('upload_time', models.DateTimeField(auto_now_add=True)),
                ('duration_seconds', models.IntegerField(blank=True, null=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recorded_videos', to='monitor_app.agent')),
            ],
            options={
                'verbose_name_plural': 'Recorded Videos',
                'ordering': ['-upload_time'],
            },
        ),
    ]
