# Generated by Django 5.2.3 on 2025-06-25 05:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agent',
            options={},
        ),
        migrations.AlterModelOptions(
            name='agentdata',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterModelOptions(
            name='keylog',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterModelOptions(
            name='recordedvideo',
            options={'ordering': ['-upload_time']},
        ),
        migrations.RemoveField(
            model_name='agent',
            name='download_bytes',
        ),
        migrations.RemoveField(
            model_name='agent',
            name='keystroke_count',
        ),
        migrations.RemoveField(
            model_name='agent',
            name='mouse_event_count',
        ),
        migrations.RemoveField(
            model_name='agent',
            name='network_type',
        ),
        migrations.RemoveField(
            model_name='agent',
            name='typed_keys',
        ),
        migrations.RemoveField(
            model_name='agent',
            name='upload_bytes',
        ),
        migrations.RemoveField(
            model_name='agentdata',
            name='typed_keys',
        ),
        migrations.AlterField(
            model_name='agent',
            name='agent_id',
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='agent',
            name='capture_interval_seconds',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='agent',
            name='friday_active_end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='agent',
            name='friday_active_start',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='agent',
            name='monday_active_end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='agent',
            name='monday_active_start',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='agent',
            name='saturday_active_end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='agent',
            name='saturday_active_start',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='agent',
            name='sunday_active_end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='agent',
            name='sunday_active_start',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='agent',
            name='thursday_active_end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='agent',
            name='thursday_active_start',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='agent',
            name='tuesday_active_end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='agent',
            name='tuesday_active_start',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='agent',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='agent',
            name='wednesday_active_end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='agent',
            name='wednesday_active_start',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='agentdata',
            name='keystroke_count',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='agentdata',
            name='mouse_event_count',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='agentdata',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='keylog',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keylogs', to='monitor_app.agent'),
        ),
        migrations.AlterField(
            model_name='keylog',
            name='is_messaging_log',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='keylog',
            name='key_sequence',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='keylog',
            name='source_app',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='keylog',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='recordedvideo',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='monitor_app.agent'),
        ),
    ]
