# Generated by Django 5.2.3 on 2025-06-25 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor_app', '0002_alter_agent_options_alter_agentdata_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='keylog',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Keystroke Log', 'verbose_name_plural': 'Keystroke Logs'},
        ),
        migrations.AlterField(
            model_name='keylog',
            name='key_sequence',
            field=models.TextField(help_text='The captured sequence of keystrokes.'),
        ),
        migrations.AlterField(
            model_name='keylog',
            name='source_app',
            field=models.CharField(help_text='The application or website where typing occurred.', max_length=255),
        ),
    ]
