# Generated by Django 5.2.3 on 2025-06-27 05:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor_app', '0003_alter_keylog_options_alter_keylog_key_sequence_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recordedvideo',
            options={'ordering': ['-upload_time'], 'verbose_name_plural': 'Recorded Videos'},
        ),
        migrations.AlterField(
            model_name='recordedvideo',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recorded_videos', to='monitor_app.agent'),
        ),
    ]
