# Generated by Django 5.2.3 on 2025-06-27 05:33

import monitor_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor_app', '0004_alter_recordedvideo_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recordedvideo',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to=monitor_app.models.video_upload_path),
        ),
    ]
