# Generated by Django 5.2.3 on 2025-06-27 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor_app', '0005_alter_recordedvideo_video_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='is_live_streaming',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='agent',
            name='live_stream_url',
            field=models.URLField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='recordedvideo',
            name='is_live_stream',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='recordedvideo',
            name='stream_url',
            field=models.URLField(blank=True, max_length=512, null=True),
        ),
    ]
