# Generated by Django 5.2.3 on 2025-06-27 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor_app', '0006_agent_is_live_streaming_agent_live_stream_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='is_live_streaming_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
