# Generated by Django 5.2.3 on 2025-06-30 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor_app', '0007_agent_is_live_streaming_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='is_video_recording_enabled',
            field=models.BooleanField(default=False, help_text='Whether video recording is enabled for this agent'),
        ),
    ]
