# Generated by Django 5.2.3 on 2025-06-30 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor_app', '0009_agent_is_screenshot_capturing_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='is_email_monitoring_enabled',
            field=models.BooleanField(default=False, help_text='Whether email monitoring is enabled for this agent'),
        ),
        migrations.AddField(
            model_name='agent',
            name='is_keystroke_logging_enabled',
            field=models.BooleanField(default=False, help_text='Whether keystroke logging is enabled for this agent'),
        ),
    ]
